version: '3.8'

services:
  backend:
    build: .
    container_name: kalpi-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - kalpi-net
    environment:
      - PYTHONPATH=/app/backend  

  frontend:
    build: .
    container_name: kalpi-frontend
    command: streamlit run frontend/app.py
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://kalpi-backend:8000  # This tells app.py where the backend is
    depends_on:
      - backend
    networks:
      - kalpi-net

networks:
  kalpi-net:
    driver: bridge